### ISSUE TITLE
Add a real time distance indicator LED

### ISSUE THREAD

**Issue by pelinquin** [eellak/epidose#11]
Great project Diomidis !

Just an advice while you are building the PCB.
Could you add another led that indicates the real-time distance to other beacons ?
This is to follow my old idea https://adox.io/bulle.pdf

Could be: 
off -> nobody around (green status in bulle)
blinking -> someone around but at safe distance (orange status in bulle) 
on -> someone too close to you...better move back (red status in bulle)
It does not matter if distance threshold is not accurate
Of course, the contact is registered only if you stay a long time with real-time led on.

This led may also help for BLE calibration

Laurent

**Comment by dspinellis** [comment]
Nice! I was thinking to have (at least in the prototype) a series of LEDs.  This could be used to indicate both distance (as you suggest, but with an increasing number of LEDs) and cumulative exposure over a sliding time window.  However, the second will also register family members, without the possibility of excluding them due to the use of a random MAC address.  Consequently, I think your proposal is the only realistic one.  The LED could flash more frequently as a device comes nearer.  So we have

* Flashing green: normal operation
* Orange: distance indicator
* Red: possibly infected\

A battery low indicator could be farther away.

What do you mean by "bulle"?
