### ISSUE TITLE
Verify, validate, and integrate production hardware

### ISSUE THREAD

**Issue by dspinellis** [eellak/epidose#36]
* [x] Charging LED
* [x] Over-discharge protection
* [x] Over-charge protection
* [x] Reset
* [x] Power level monitoring
* [x] Power off
* [x] Power restoration during scheduled power off
* [x] Real time clock
* [x] Share switch
* [x] WiFi switch
* [x] Status LED
* [x] Bluetooth signal strength
* [x] WiFi signal strength

**Comment by dspinellis** [comment]
## Comments for next release
* [ ] Can we adjust the reset button to signal a graceful shutdown on short press and perform a hard reset on long press?
* [ ] Charging LED should indicate end of charging (e.g. by slow blinking when charging and permanent green when finished)
 * [ ] Better use orange for battery low notification to reserve the red color for exposure notification.
* [x] Optimize and clarify battery charging. Currently, starting from 3.5V, it takes 10h to reach 4V and 20h to reach 4.14V.
* [ ] Reduce the diameter of the switch access holes to that of a paper clip wire.
* [ ] Add box and battery icon on the three power holes
* [ ] Add box and virus icon to the share/status/wifi holes
* [ ] Add GFOS URL

## Other comments (not for action)
* Red LED is negative logic (issue addressed in software)
* Low power is indicated at about 3.54 V
* Power is shut down below 3.4 V; performing an orderly shutdown at 3.45 V gives us about 30' of headroom
* Charging seems to stop at about 4.23 V.

## Questions
* Do the values in the battery level sensing file represent voltages?  Why is their range so narrow?
* What is the SPI protocol? Why is a fake transfer required before getting the voltage?
* spidev isn't [documenting](https://pypi.org/project/spidev/) any exceptions. Any reason you catch them in the example?
* How long after sending a power-down command to the microcontroller is the power removed?

**Comment by dspinellis** [comment]
Example of orderly shutdown and subsequent restart
```
2020-09-11 22:29:08,779: Battery 3.48071484375
2020-09-11 22:29:11,166: Battery 3.477533203125
2020-09-11 22:29:13,557: Battery 3.436171875
2020-09-11 22:29:13,563: Battery exchausted; shutting down
2020-09-11 22:30:02,981: Battery 3.4823056640625
2020-09-11 22:30:03,127: beacon_tx not running
2020-09-11 22:30:05,134: Battery 3.4759423828125
2020-09-11 22:30:05,272: beacon_tx not running
2020-09-11 22:30:46,369: Battery 3.4759423828125
2020-09-11 22:30:48,884: Battery 3.4743515625
2020-09-11 22:30:51,306: Battery 3.496623046875
2020-09-11 22:30:53,686: Battery 3.496623046875
2020-09-11 22:30:56,065: Battery 3.4950322265625
2020-09-11 22:30:58,413: Battery 3.49344140625
```

**Comment by konasimakopoulos** [comment]
To answer some of the questions:
> Do the values in the battery level sensing file represent voltages? Why is their range so narrow?

The microcontroller returns the current battery voltage. An approximation of the manufacturer's discharge curve was created and is used to convert the battery voltage to a percentage. The microcontroller will allow the RPi to operate until the battery gets to about 3.3-3.4 V. After that, the 5V rail will turn off and the microcontroller will enter sleep mode to minimize battery power drain, until a charger is connected. 
The range of the values is narrow due to the shape of the battery's discharge curve. However this range represents most of the battery's energy capacity with only a small part left over to prevent complete battery discharge when the microcontroller is in sleep mode.

> What is the SPI protocol? Why is a fake transfer required before getting the voltage?

The communication protocol implemented generally requires two transfers to actually get data from the microcontroller. The first transfer is the data request, where the microcontroller prepares the buffer that will be transmitted during the next transfer (and at the same time transmits the previous buffer, or if this is the first command, transmits an empty buffer). The second transfer is the "fake" one where the RPi sends an empty buffer and receives the previously requested data. 

>     * spidev isn't [documenting](https://pypi.org/project/spidev/) any exceptions. Any reason you catch them in the example?

During development we noticed that if the user has SPI disabled for any reason, spidev will raise an exception. The try block was added for that reason.

>     * How long after sending a power-down command to the microcontroller is the power removed?

The microcontroller turns off the 5V rail 30s after receiving the shutdown (or restart) command.

**Comment by dspinellis** [comment]
Thank you; quite clear!

**Comment by konasimakopoulos** [comment]
>  Can we adjust the reset button to signal a graceful shutdown on short press and perform a hard reset on long press?

This could be tricky. The Reset button is currently directly connected to the reset pin of the microcontroller. Maybe if the microcontroller sampled another button. However that would change the communication protocol as currently only the RPi initiates communication.

**Comment by dspinellis** [comment]
OK, we will then use a long press of the WiFi switch for powering off.
